# -*- coding: utf-8 -*-
"""Fin 330 Final project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZV4nhlzekoigZXkE1G5E16bZ5WYM4_ir

# FIN 330 Final Project - Stock Analytics & Portfolio Dashboard

## Setup
- yfinance pulls real stock data from Yahoo Finance
- pandas handles data as tables (DataFrames)
- numpy does math calculations
- matplotlib makes charts
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

"""# PART 1: Individual Stock Analysis"""

# Step 1: Download stock data
# Change "AAPL" to whatever stock you are analyzing
# We grab 6 months of daily closing prices

ticker = "AAPL"
data = yf.download(ticker, period="6mo", auto_adjust=False)
data.head()

# Pull out just the closing price column
# .squeeze() turns it from a DataFrame into a simple Series (list of numbers)

close = data["Close"].squeeze()

# Step 2: Calculate Moving Averages
# A moving average smooths out daily price swings to show the trend
# .rolling(20).mean() = average of the last 20 days, updated each day

data["MA20"] = data["Close"].rolling(20).mean()
data["MA50"] = data["Close"].rolling(50).mean()

# Plot price vs. moving averages
plt.figure(figsize=(10, 6))
plt.plot(data["Close"], label="Price")
plt.plot(data["MA20"], label="20-Day MA")
plt.plot(data["MA50"], label="50-Day MA")
plt.legend()
plt.title(f"{ticker} - Price and Moving Averages")
plt.show()

# Grab the most recent values using iloc
# iloc[-1] = the last row (today's price)
# iloc[-20:].mean() = average of the last 20 rows

if not close.empty:
    current_price = close.iloc[-1]
    st.write(f"The current price is {current_price}")
else:
    st.error("No data found for this ticker. Please check the symbol and try again.")
print(f"Current Price: ${current_price:.2f}")
print(f"20-Day MA:     ${ma_20:.2f}")
print(f"50-Day MA:     ${ma_50:.2f}")

# Determine trend direction
# If price is above both MAs, the stock is in an uptrend
# If below both, it's in a downtrend
if current_price > ma_20 and current_price > ma_50:
    trend = "Strong Uptrend"
elif current_price < ma_20 and current_price < ma_50:
    trend = "Strong Downtrend"
else:
    trend = "Mixed Trend"

print(f"Trend: {trend}")

# Step 3: RSI (Relative Strength Index)
# RSI measures momentum - how fast prices are moving up vs down
# It ranges from 0 to 100
# Above 70 = overbought (might drop), Below 30 = oversold (might rise)

# Calculate daily price changes
delta = close.diff()

# Separate gains (positive changes) and losses (negative changes)
gains = delta.clip(lower=0)
losses = -delta.clip(upper=0)

# Average gains and losses over 14 days
avg_gain = gains.rolling(14).mean()
avg_loss = losses.rolling(14).mean()

# RS = average gain divided by average loss
# RSI formula converts that into a 0-100 scale
rs = avg_gain / avg_loss
rsi = 100 - (100 / (1 + rs))

# Get the most recent RSI value
current_rsi = rsi.iloc[-1]
print(f"Current RSI: {current_rsi:.2f}")

# Interpret the RSI signal
if current_rsi > 70:
    rsi_signal = "Overbought - Possible Sell Signal"
elif current_rsi < 30:
    rsi_signal = "Oversold - Possible Buy Signal"
else:
    rsi_signal = "Neutral"

print(f"RSI Signal: {rsi_signal}")

# Step 4: Volatility
# Volatility tells us how much a stock price jumps around day to day
# Higher volatility = more risk
# We annualize it by multiplying by sqrt(252) - 252 trading days in a year

daily_returns = close.pct_change()
volatility = daily_returns.rolling(20).std().iloc[-1] * np.sqrt(252) * 100
print(f"Annualized Volatility: {volatility:.2f}%")

if volatility > 40:
    vol_level = "High Volatility"
elif volatility > 25:
    vol_level = "Medium Volatility"
else:
    vol_level = "Low Volatility"

print(f"Volatility Level: {vol_level}")

# Step 5: Final Trading Recommendation
# Based on trend, RSI, and volatility - give a Buy / Sell / Hold

if trend == "Strong Uptrend" and rsi_signal == "Neutral":
    recommendation = "Buy"
elif trend == "Strong Downtrend" or rsi_signal == "Overbought - Possible Sell Signal":
    recommendation = "Sell"
else:
    recommendation = "Hold"

print(f"\n--- Final Recommendation: {recommendation} ---")
print(f"Trend: {trend}")
print(f"RSI Signal: {rsi_signal}")
print(f"Volatility: {vol_level}")

"""# PART 2: Portfolio Performance Dashboard"""

# Step 1: Define your 5 stocks and their weights
# Weights must add up to 1.0 (100%)
# Change these tickers and weights to whatever you choose

tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA"]
weights = [0.20, 0.20, 0.20, 0.20, 0.20]

# Step 2 & 3: Download 1 year of price data for stocks + benchmark
# SPY is the S&P 500 ETF - standard benchmark to compare against

all_tickers = tickers + ["SPY"]
raw = yf.download(all_tickers, period="1y", auto_adjust=False)

# Pull just the closing prices for all tickers
prices = raw["Close"]
prices.head()

# Step 4: Calculate daily returns
# pct_change() gives the % change from one day to the next

returns = prices.pct_change().dropna()

# Separate stock returns from benchmark
stock_returns = returns[tickers]
spy_returns = returns["SPY"]

# Calculate portfolio daily return
# Each stock's return is multiplied by its weight, then summed
# This gives us one daily return number for the whole portfolio
portfolio_returns = (stock_returns * weights).sum(axis=1)

# Step 5: Performance Metrics
# Total return: how much $1 grew over the year
# (1 + daily return) compounded every day

total_return = (1 + portfolio_returns).prod() - 1
benchmark_return = (1 + spy_returns).prod() - 1

print(f"Portfolio Total Return:  {total_return * 100:.2f}%")
print(f"Benchmark (SPY) Return:  {benchmark_return * 100:.2f}%")
print(f"Outperformance:          {(total_return - benchmark_return) * 100:.2f}%")

# Annualized volatility (same formula as Part 1)
port_volatility = portfolio_returns.std() * np.sqrt(252) * 100
print(f"Portfolio Volatility:    {port_volatility:.2f}%")

# Sharpe Ratio: return per unit of risk
# Higher = better. Above 1.0 is generally considered good
# We assume a 0% risk-free rate to keep it simple
sharpe = (portfolio_returns.mean() / portfolio_returns.std()) * np.sqrt(252)
print(f"Sharpe Ratio:            {sharpe:.2f}")

# Step 6: Plot portfolio vs benchmark over time
# Cumulative return shows the growth of $1 invested on day 1

cumulative_portfolio = (1 + portfolio_returns).cumprod()
cumulative_spy = (1 + spy_returns).cumprod()

plt.figure(figsize=(10, 6))
plt.plot(cumulative_portfolio, label="My Portfolio")
plt.plot(cumulative_spy, label="SPY Benchmark")
plt.legend()
plt.title("Portfolio vs. SPY - 1 Year Cumulative Return")
plt.ylabel("Growth of $1")
plt.show()
